assignment/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'assignment.views.home', name='home'),
    # url(r'^assignment/', include('assignment.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

realtdb/urls.py
#-*- coding:utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('realtdb.views',
    url('^houses/$', 'house_list', name="realtdb-houses"),
    url('^apartments/$', 'apartment_list', name="realtdb-apartments"),
)

realtdb/models.py
#-*- coding:utf-8 -*-

from django.db import models


class Realtor(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)


class House(models.Model):
    realtor = models.ForeignKey(Realtor)
    address = models.CharField(max_length=100)
    area = models.FloatField(help_text=u"In square meters")
    price = models.DecimalField(max_digits=11, decimal_places=2)


class Apartment(House):
    rooms = models.IntegerField()
    floor = models.IntegerField()
    floors = models.IntegerField()

realtdb/views.py
#-*- coding:utf-8 -*-

from decimal import Decimal
import random

from django.shortcuts import render, redirect
from django import forms

from realtdb.models import Realtor, House, Apartment


class HouseForm(forms.Form):
    address = forms.CharField(max_length=100)
    area = forms.IntegerField()
    price = forms.IntegerField()


class ApartmentForm(HouseForm):
    rooms = forms.IntegerField()
    floor = forms.IntegerField()
    floors = forms.IntegerField()


def house_list(request):
    result = {}

    if request.method == "POST":
        form = HouseForm(request.POST)
        if form.is_valid():
            random_realtor = random.choice(Realtor.objects.all())
            House.objects.create(
                realtor=random_realtor,
                address=request.POST['address'],
                area=float(request.POST['area']),
                price=Decimal(request.POST['price']))
            return redirect(request.path)
        else:
            result['error'] = 'Form validation error'

    result['house_list'] = House.objects.order_by('-id').select_related()
    return render(request, "realtdb/houses.html", result)


def apartment_list(request):
    result = {}

    if request.method == "POST":
        form = ApartmentForm(request.POST)
        if form.is_valid():
            random_realtor = random.choice(Realtor.objects.all())
            Apartment.objects.create(
                realtor=random_realtor,
                address=request.POST['address'],
                area=float(request.POST['area']),
                price=Decimal(request.POST['price']),
                rooms=int(request.POST['rooms']),
                floor=int(request.POST['floor']),
                floors=int(request.POST['floors']),
            )
            return redirect(request.path)
        else:
            result['error'] = 'Form validation error'

    result['apartment_list'] = Apartment.objects.order_by('-id').select_related()
    return render(request, "realtdb/apartments.html", result)

realtdb/templates/realtdb/apartments.html
{% extends "base.html" %}

{% block title %}List of apartments{% endblock %}

{% block navbar %}
  <div class="navbar">
	<div class="navbar-inner">
	  <ul class="nav">
	    <li><a href="{% url 'realtdb-houses' %}">Houses</a></li>
        <li class="active"><a>Apartments</a></li>
	  </ul>
	</div>
  </div>
{% endblock %}

{% block content %}
<h1>Directory of apartments</h1>

<form action="." method="post">{% csrf_token %}
    <p>{{ error }}</p>
    <table>
        <tr><td><label for="id_address">Address: </label></td><td><input id="id_address" type="text" name="address" /></td></tr>
        <tr><td><label for="id_area">Area: </label></td><td><input id="id_area" type="text" name="area" /></td></tr>
        <tr><td><label for="id_price">Price: </label></td><td><input id="id_price" type="text" name="price" /></td></tr>
        <tr><td><label for="id_rooms">Rooms: </label></td><td><input id="id_rooms" type="text" name="rooms" /></td></tr>
        <tr><td><label for="id_floor">Floor: </label></td><td><input id="id_floor" type="text" name="floor" /></td></tr>
        <tr><td><label for="id_floors">Total floors: </label></td><td><input id="id_floors" type="text" name="floors" /></td></tr>
    </table>
    <p><input type="submit" value="Add to list" /></p>
</form>

<h2>List of known apartments</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Address</th>
            <th>Area (m<sup>2</sup>)</th>
            <th>Rooms</th>
            <th>Floor</th>
            <th>Price</th>
            <th>Realtor</th>
        </tr>
    </thead>
    <tbody>
    {% for apartment in apartment_list %}
        <tr>
            <td>{{ apartment.address }}</td>
            <td>{{ apartment.area }}</td>
            <td>{{ apartment.rooms }}</td>
            <td>{{ apartment.floor }} / {{ apartment.floors }}</td>
            <td>{{ apartment.price }}</td>
            <td>{{ apartment.realtor.name }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

realtdb/templates/realtdb/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}List of houses{% endblock %}</title>
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">
      {% block navbar %}
      {% endblock %}

      {% block content %}
      {% endblock content %}

      {% block query_debug %}
      {% if debug %}
      <button type="button" class="btn" data-toggle="collapse" data-target="#debug">Show SQL</button>

      <div id="debug" class="collapse">
        <table class="table table-condensed table-bordered">
          <col width="1"></col>
          <col></col>
          <col width="1"></col>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">SQL</th>
              <th scope="col">Time</th>
            </tr>
          </thead>
          <tbody>
            {% for query in sql_queries %}
	    <tr class="{% cycle odd,even %}">
              <td>{{ forloop.counter }}</td>
              <td>{{ query.sql|escape }}</td>
              <td>{{ query.time }}</td>
            </tr>
	    {% endfor %}
          </tbody>
        </table>
      </div>
      {% endif %}
      {% endblock query_debug %}
    </div>
  </body>
</html>

realtdb/templates/realtdb/houses.html
{% extends "base.html" %}

{% block title %}List of houses{% endblock %}

{% block navbar %}
  <div class="navbar">
	<div class="navbar-inner">
	  <ul class="nav">
        <li class="active"><a>Houses</a></li>
        <li><a href="{% url 'realtdb-apartments' %}">Apartments</a></li>
	  </ul>
	</div>
  </div>
{% endblock %}

{% block content %}
<h1>Directory of houses</h1>

<form action="." method="post">{% csrf_token %}
    <p>{{ error }}</p>
    <table>
      <tr><td><label for="id_address">Address: </label></td><td><input id="id_address" type="text" name="address" /></td></tr>
      <tr><td><label for="id_area">Area: </label></td><td><input id="id_area" type="text" name="area" /></td></tr>
      <tr><td><label for="id_price">Price: </label></td><td><input id="id_price" type="text" name="price" /></td></tr>
    </table>
    <p><input type="submit" value="Add to list" /></p>
</form>

<h2>List of known houses</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Address</th>
            <th>Area (m<sup>2</sup>)</th>
            <th>Price</th>
            <th>Realtor</th></tr>
    </thead>
    <tbody>
        {% for house in house_list %}
        <tr>
            <td>{{ house.address }}</td>
            <td>{{ house.area }}</td>
            <td>{{ house.price }}</td>
            <td>{{ house.realtor.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}